server:
  port: 9000
spring:
  kafka:
    jaas:
      enabled: true
      options:
        debug: true
        doNotPrompt: true
        useKeyTab: true
        storeKey: true
        keyTab: /Users/labuser/Workspace/kafkaTester/src/main/resources/cop-sa.keytab
        principal: cop-sa-spu-wvp-134-n
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: GSSAPI
        kerberos:
          service:
            name: kafka
    consumer:
      bootstrap-servers: dev-kafka.kafkausc1dev.solutions.corelogic.com:9092
      group-id: spatial_us-wvsplatform-kafka-to-bq-spike
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: dev-kafka.kafkausc1dev.solutions.corelogic.com:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable:
          idempotence: false
